/*-----------------------------------------------------------------------------
Filename: RTC.c
Description: RTC function
Generated by Musa ÇUFALCI. Friday February 08 08.02.2019
----------------------------------------------------------------------------- */
/*
-----------------------------------------------------------------------------
A U T H O R I D E N T I T Y
-----------------------------------------------------------------------------
---------- --------------------- --------------------------------------------
Musa  ÇUFALCI
-----------------------------------------------------------------------------
R E V I S I O N H I S T O R Y
-----------------------------------------------------------------------------
Date Author Modification Description
Type
---------- ------ ------------- ---------------------------------------------
08.02.2019 MK Added First creating after project editing
-----------------------------------------------------------------------------
*/


#include "RTC.h"

/******************************************************************************
* Global variables
******************************************************************************/
volatile UINT32 button_counter = 0;
volatile UINT32 timeout_counter = 0;
volatile UINT32 step_counter = 0;
volatile UINT32 ignition_counter = 0;

/***********************************************************************************************
* @brief    RTC_Init   Initializes the Real Time Counter Module
* @param    none
* @return   none
************************************************************************************************/ 

void RTC_Init(void)
{
	RTCCTL1_COMPE = 1;		//The read/write bit enables the clock compensation mechanism for clock frequency errors.
	RTCMOD =  32768;		//Modulo register configuration
	RTCCCR_Q = 3;
	RTCCCR_CCS = 0;
	RTCCTL2_CLKSRC = 0;		// RTCCLK is from OSCCLK_32K
	RTCCTL2_RTCPS = 3;      
	RTCCTL1_RTCEN = 1;		//RTC function is enabled.
}

void RTI_Init(void)
{
	CPMUCLKS_RTIOSCSEL = 0x0;          // RTI clock source is IRCCLK.
	CPMURTI_RTDEC = 0x1;               // Decimal based divider value
	CPMURTI_RTR = 0x0;                 // RTI Frequency Divide Rates for RTDEC=1   1x10^3
	CPMUINT_RTIE = 0x1;                // Enable RTI	
}

interrupt VectorNumber_Vrti void clock_rti_ticks(void)
{
	CPMUIFLG_RTIF=1;
	
	u32_clock_ticks++;
	if(button_counter < 0xFFFFFFFF)
		button_counter++;
	if(timeout_counter < 0xFFFFFFFF)
		timeout_counter++;
	if(step_counter < 0xFFFFFFFF)
		step_counter++;
	if(ignition_counter < 0xFFFFFFFF)
		ignition_counter++;
}
